site_name: "REALM-AI: Game Analytics"
theme:
  name: material
  logo: assets/logo1.png
  favicon: assets/logo1.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions: 
  - attr_list 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/realm-ai-project

nav:
  # - Introduction: index.md
  - Quick Start Guide: index.md
  - Game Plugin Subsystem:
    - Overview: game_plugin_subsystem/overview.md
    - Installing the Unity Package: game_plugin_subsystem/installation_unity.md
    - Setting up the Python Environment: game_plugin_subsystem/installation_python.md
    - Project Requirements, Setting up the Player Prefab: game_plugin_subsystem/installation_player.md
    - Configuring the Realm AI Module: game_plugin_subsystem/installation_configuration.md
    - Final Tips and Instructions: game_plugin_subsystem/installation_tips.md
    - Known Issues: game_plugin_subsystem/known_issues.md
  - RL Subsystem: 
    - Description: rl_subsystem/description.md
    - Quick Start Guide: rl_subsystem/getting_started.md
    - Realm-Tune: 
      - Hyperparameter Tuning: rl_subsystem/realm-tune/hyperparameter_tuning.md
      - Configuration: rl_subsystem/realm-tune/configuration.md
      - Features and Limitations: rl_subsystem/realm-tune/features_and_limits.md
    - Wandb-Mlagents-Learn:
      - Usage Guide: rl_subsystem/wandb-mlagents-learn/usage-guide.md
  # - Analysis Subsystem:
  #   - Description: analysis_subsystem/description.md
  #   - Heatmaps: analysis_subsystem/heatmaps.md
  - Reporting Subsystem:
    - Description: reporting_subsystem/description.md
  - Python GUI:
    - Description: python_gui/description.md
    - User Guide: python_gui/user_guide.md
  - Feature Request: feature_request/todo.md