site_name: REALM_AI 
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions: 
  - attr_list 

nav:
  - Introduction: index.md
  - Installation: installation.md
  - RL Subsystem: 
    - Description: rl_subsystem/description.md
    - Hyperparameter Tuning: rl_subsystem/hyperparameter_tuning.md
    - User Guide: rl_subsystem/user_guide.md
  - Analysis Subsystem:
    - Description: analysis_subsystem/description.md
    - Heatmaps: analysis_subsystem/heatmaps.md
  - Reporting Subsystem:
    - Description: reporting_subsystem/description.md
  - Feature Request: todo.md